eventex/subscriptions/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url

urlpatterns = patterns('eventex.subscriptions.views',
    url(r'^$', 'subscribe', name='subscribe'),
    url(r'^(\d+)/$', 'detail', name='detail'),
)

eventex/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^inscricao/', include('eventex.subscriptions.urls', namespace='subscriptions')),

    url(r'', include('eventex.core.urls', namespace='core')),
    url(r'^admin/', include(admin.site.urls)),
)

eventex/subscriptions/models.py
# coding: utf-8
from django.db import models
from django.utils.translation import ugettext_lazy as _

class Subscription(models.Model):
    name = models.CharField(_('nome'), max_length=100)
    cpf = models.CharField(_('CPF'), max_length=11, unique=True)
    email = models.EmailField(_('email'), blank=True)
    phone = models.CharField(_('telefone'), max_length=20, blank=True)
    created_at = models.DateTimeField(_('criado em'), auto_now_add=True)
    paid = models.BooleanField(_('Pago'))

    class Meta:
        ordering = ['created_at']
        verbose_name = _(u'inscrição')
        verbose_name_plural = _(u'inscrições ')

    def __unicode__(self):
        return self.name

eventex/subscriptions/forms.py
# coding: utf-8
from django import forms
from django.utils.translation import ugettext as _
from django.core.exceptions import ValidationError
from django.core.validators import EMPTY_VALUES
from eventex.subscriptions.models import Subscription

def CPFValidator(value):
    if not value.isdigit():
        raise ValidationError(_(u'CPF deve conter apenas numeros'))
    if len(value) != 11:
        raise ValidationError(_(u'CPF deve ter 11 digitos'))

class PhoneWidget(forms.MultiWidget):
    def __init__(self, attrs=None):
        widgets = (
            forms.TextInput(attrs=attrs),
            forms.TextInput(attrs=attrs))
        super(PhoneWidget, self).__init__(widgets, attrs)

    def decompress(self, value):
        if not value:
            return [None, None]
        return value.split('-')

class PhoneField(forms.MultiValueField):
    widget = PhoneWidget

    def __init__(self, *args, **kwargs):
        fields = (forms.IntegerField(),
                  forms.IntegerField())
        super(PhoneField, self).__init__(fields, *args, **kwargs)

    def compress(self, data_list):
        if not data_list:
            return ''
        if data_list[0] in EMPTY_VALUES:
            raise forms.ValidationError(_(u'DDD inválido.'))
        if data_list[1] in EMPTY_VALUES:
            raise forms.validators(_(u'Número inválido.'))
        return '%s-%s' % tuple(data_list)

class SubscriptionForm(forms.ModelForm):
    phone = PhoneField(label=_('Telefone'), required=False)
    class Meta:
        model = Subscription
        fields = ('name', 'email', 'cpf', 'phone',)
        #exclude = ('paid',)

    def __init__(self, *args, **kwargs):
        super(SubscriptionForm, self).__init__(*args, **kwargs)

        self.fields['cpf'].validators.append(CPFValidator)

    def clean_name(self):
        name = self.cleaned_data['name']
        #words = name.split() # split sem valor por padrão faz split por espaço
        #for index, word in enumerate(words):
        #    words[index] = word.capitalize()
        # o código acima foi refatorado para a linha abaixo usando lambda
        words = map(lambda w: w.capitalize(), name.split())
        capitalized_name = ' '.join(words)
        return capitalized_name

    def clean(self):
        "esse clean é executado depois que todo ciclo de validação já foi executado"
        super(SubscriptionForm, self).clean()

        #if not self.cleaned_data['email'] and \
        #   not self.cleaned_data['phone']:
        # Dica: sempre que precisar pegar valor do cleaned_data é melhor usar o get e não a chave
        # isso porque pela chave se não existir retorna erro 500 e pelo get não retorna erro
        if not self.cleaned_data.get('email') and \
           not self.cleaned_data.get('phone'):
            raise ValidationError(_(u'Informe seu email ou telefone'))

        return self.cleaned_data

eventex/subscriptions/views.py
# coding: utf-8
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from eventex.subscriptions.forms import SubscriptionForm
from eventex.subscriptions.models import Subscription

def subscribe(request):
    if request.method == 'POST':
        return create(request)
    else:
        return new(request)


def new(request):
    return render(request, 'subscriptions/subscription_form.html',
            {'form': SubscriptionForm()})

def create(request):
    form = SubscriptionForm(request.POST)
    if not form.is_valid():
        return render(request, 'subscriptions/subscription_form.html',
                {'form': form})

    obj = form.save()
    return HttpResponseRedirect('/inscricao/%d/' % obj.pk)

def detail(request, pk):
    subscription = get_object_or_404(Subscription, pk=pk)
    return render(request, 'subscriptions/subscription_detail.html',
        {'subscription': subscription})

eventex/subscriptions/templates/subscriptions/subscription_detail.html
{% extends 'base.html' %}

{% block content %}

    <p>
      <div class="alert alert-success">
        Parabéns {{ subscription.name }},
      </div>
    </p>


    <p>Sua inscrição foi realizada em:
        <span class="badge badge-inverse">
            {{ subscription.created_at|date:"d/m/Y" }}.
        </span>
    </p>
    <p>Em breve, entraremos em contato pelo
        {% if subscription.phone %}
            telefone: <span class="badge badge-inverse">{{ subscription.phone }}</span>
        {% else %}
            e-mail: <span class="badge badge-inverse">{{ subscription.email }}</span>
        {% endif %}
    </p>

    <a class="btn btn-primary" href="/">OK</a>
{% endblock content %}

eventex/subscriptions/templates/subscriptions/subscription_form.html
{% extends 'base.html' %}

{% block content %}

    <h1>Formulário de inscrição</h1>
    <!-- Form -->
    <form action="." method="POST" class="forms-horizontal">
        {% csrf_token %}
        <fieldset class="form-actions">
            {{ form.non_field_errors }}
            <div class="control-group">
                <label for="{{ form.name.id_for_label }}">{{ form.name.label }}:</label>
                <div class="controls">
                    {% if form.name.value %}
                        <input id="id_name" type="text" class="form-control span10" name="name" maxlength="100" value={{ form.name.value }} />
                    {% else %}
                        <input id="id_name" type="text" class="form-control span10" name="name" maxlength="100" />
                    {% endif %}
                    {{ form.name.errors }}
                </div>            
            </div>
            <div class="control-group">
                <label for="form.cpf.id_for_label">{{ form.cpf.label }}:</label>
                <div class="controls">
                    {% if form.cpf.value %}
                        <input id="id_cpf" type="text" name="cpf" class="form-control span3" maxlength="11" value="{{ form.cpf.value }}"/>
                    {% else %}
                        <input id="id_cpf" type="text" name="cpf" class="form-control span3" maxlength="11" />
                    {% endif %}
                    {{ form.cpf.errors }}
                </div>            
            </div>
            <div class="control-group">
                <label for="form.email.id_for_label">{{ form.email.label }}:</label>
                <div class="controls">
                    {% if form.email.value %}
                        <input id="id_email" type="text" class="form-control span10" name="email" maxlength="75" value="{{ form.email.value }}" />
                    {% else %}
                        <input id="id_email" type="text" class="form-control span10" name="email" maxlength="75" />
                    {% endif %}
                    {{ form.email.errors }}
                </div>            
            </div>
            <div class="control-group">
                <label for="form.phone.id_for_label">{{ form.phone.label }}:</label>
                <div class="controls">
                    {% if form.phone.value %}
                        (<input id="id_phone_0" type="text" name="phone_0" class="form-control span1" maxlength="20" value="{{ form.phone_0.value }}"/>)
                        <input id="id_phone_1" type="text" name="phone_1" class="form-control span3" maxlength="20" value="{{ form.phone_1.value }}"/>
                    {% else %}
                        (<input id="id_phone_0" type="text" name="phone_0" class="form-control span1" maxlength="20" />)
                        <input id="id_phone_1" type="text" name="phone_1" class="form-control span3" maxlength="20" />
                    {% endif %}
                    {{ form.phone.errors }}
                </div>                           
            </div>
            <input type="submit" value="Enviar" class="btn btn-primary">
            <a href="/" class="btn">Cancelar</a>            
        </fieldset>
    </form>
    <!-- Form -->
{% endblock content %}