eventex/core/urls.py
# coding: utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns('eventex.core.views',
    url(r'^$', 'homepage', name='homepage'),
    url(r'^palestrantes/(?P<slug>[\w-]+)/$', 'speaker_detail', name='speaker_detail'),
    url(r'^palestrantes/$', 'speaker_list', name='speaker_list'),
    url(r'^palestras/', 'talk_list', name='talk_list'),
    url(r'^palestra/(\d+)/$', 'talk_detail', name='talk_detail'),

)

eventex/subscriptions/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url

urlpatterns = patterns('eventex.subscriptions.views',
    url(r'^$', 'subscribe', name='subscribe'),
    url(r'^(\d+)/$', 'detail', name='detail'),
)

eventex/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^inscricao/', include('eventex.subscriptions.urls', namespace='subscriptions')),

    url(r'', include('eventex.core.urls', namespace='core')),
    url(r'^admin/', include(admin.site.urls)),
)

eventex/core/models.py
# coding: utf-8
from django.db import models
from django.utils.translation import ugettext_lazy as _
from eventex.core.managers import KindContactManager, PeriodManager

class Speaker(models.Model):
    name = models.CharField(_('Nome'), max_length=255)
    slug = models.SlugField(_('Slug'))
    url = models.URLField(_('Url'))
    description = models.TextField(_(u'Descrição'), blank=True)

    class Meta:
        verbose_name=_('palestrante')
        verbose_name_plural = _('palestrantes')

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return '/palestrantes/%s/' % self.slug           

class Contact(models.Model):
    KINDS = (
        ('P', _('Telefone')),
        ('E', _('E-mail')),
        ('F', _('Fax')),
    )
    speaker = models.ForeignKey('Speaker', verbose_name=_('palestrante')) 
    kind = models.CharField(_('tipo'), max_length=1, choices=KINDS)
    value = models.CharField(_('valor'), max_length=255)    

    objects = models.Manager()
    emails = KindContactManager('E')
    phones = KindContactManager('P')
    faxes = KindContactManager('F')

    def __unicode__(self):
        return self.value   

    def get_absolute_url(self):
        return ('core:speaker_detail', (), {'slug': self.slug}) 

class Talk(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.TimeField(blank=True)
    speakers = models.ManyToManyField('Speaker', verbose_name=_('palestrante'))

    objects = PeriodManager()

    @property
    def videos(self):
        return self.media_set.filter(kind='YT')

    @property
    def slides(self):
        return self.media_set.filter(kind='SL')    

    class Meta:
        verbose_name=_('palestra')
        verbose_name_plural = _('palestras')
        
    def __unicode__(self):
        return self.title     

    def get_absolute_url(self):
        return '/palestra/%d/' % self.pk

class Course(Talk):
    slots = models.IntegerField()
    notes = models.TextField()

    objects = PeriodManager()

class CodingCourse(Course):
    class Meta:
        proxy = True
    
    def do_some_python_stuff(self):
        return "Let's hack! at %s" % self.title    

class Media(models.Model):
    MEDIAS = (
        ('YT', _('YouTube')),
        ('SL', _('SlideShare')),
    )
    talk = models.ForeignKey('Talk', verbose_name=_('palestra')) 
    kind = models.CharField(_('Tipo'), max_length=2, choices=MEDIAS)
    title = models.CharField(_(u'Título'), max_length=200)
    media_id = models.CharField(_('ID_Ref'), max_length=255)
    media_doc = models.CharField(_('Doc_Slide'), max_length=255, default="0")

    def __unicode__(self):
        return u'%s - %s' % (self.talk.title, self.title)        

eventex/core/views.py
# coding: utf-8
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from eventex.core.models import Speaker, Talk

def homepage(request):
    return render(request, 'index.html')


def speaker_detail(request, slug):
    speaker = get_object_or_404(Speaker, slug=slug)
    context = {'speaker': speaker}
    return render(request, 'core/speaker_detail.html', context)

def speaker_list(request):
    speakers = Speaker.objects.all()
    context = {'speakers': speakers}
    return render(request, 'core/speaker_list.html', context)

def talk_detail(request, pk):
    """
     Código refatorado, foi criado as properties:
       videos e slides na model Talk,
       assim enviando talk no context, automaticamente
       terá videos e slides
    """     
    talk = get_object_or_404(Talk, pk=pk)
    context = {
        'talk': talk,          
        #'slides': talk.media_set.filter(kind='SL'),
        #'videos': talk.media_set.filter(kind='YT'),
    }
    return render(request, 'core/talk_detail.html', context)

def talk_list(request):
    context = {
        'morning_talks': Talk.objects.at_morning(),
        'afternoon_talks': Talk.objects.at_afternoon(),
    }
    return render(request, 'core/talk_list.html', context)

eventex/core/templates/base.html
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
    <title>EventeX</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/docs.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/pygments-manni.css" rel="stylesheet">

    <!-- Le styles -->
    <style type="text/css">
        body {
            padding-top: 60px;
            padding-bottom: 40px;
        }
        .content-center{
            text-align: center;
        }
    </style>
    <link href="{{ STATIC_URL }}css/bootstrap-responsive.css" rel="stylesheet">
    <link rel="shortcut icon" href="{{ STATIC_URL }}img/favicon.png">
</head>
<body>

    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
              <div class="nav-collapse collapse bs-navbar-collapse">
                <ul class="nav navbar-nav">
                  <li class="active"><a href="/">EventeX</a></li>
                  
                  <!-- inscrições -->
                  <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-pencil icon-white"></i>&nbsp;Inscrições<b class="caret"></b></a>
                      <ul class="dropdown-menu">
                        <li><a href="{% url 'subscriptions:subscribe' %}">
                            <i class="icon-plus icon-white"></i>&nbsp;Inscreva-se já</a></li>
                        <li><a href="/admin/subscriptions/subscription/" target="__blank">
                            <i class="icon-list icon-white"></i>&nbsp;Lista de Inscritos</a></li>
                      </ul>
                  </li>
                  <!-- inscrições -->

                  <!-- palestras -->
                  <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                          <i class="icon-tags icon-white"></i>&nbsp;Palestras<b class="caret"></b></a>
                      <ul class="dropdown-menu">
                        <li><a href="/admin/core/talk/add/" target="__blank">
                            <i class="icon-plus icon-white"></i>&nbsp;Cadastrar Palestra</a></li>
                        <li><a href="{% url 'core:talk_list' %}">
                            <i class="icon-list icon-white"></i>&nbsp;Lista de Palestras</a></li>
                      </ul>
                  </li>
                  <!-- palestras -->

                  <!-- palestrantes -->
                  <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                          <i class="icon-user icon-white"></i>&nbsp;Palestrantes<b class="caret"></b></a>
                      <ul class="dropdown-menu">
                        <li><a href="/admin/core/speaker/add/" target="__blank">
                            <i class="icon-plus icon-white"></i>&nbsp;Cadastrar Palestrante</a></li>
                        <li><a href="{% url 'core:speaker_list' %}">
                            <i class="icon-list icon-white"></i>&nbsp;Lista de Palestrantes</a></li>
                      </ul>
                  </li>
                  <!-- palestrantes -->

                  <!-- sobre -->
                  <li>
                      <a href="#myModal" role="button" data-toggle="modal">
                      <i class="icon-info-sign icon-white"></i>&nbsp;Sobre</a>
                  </li>
                  <!-- sobre -->

                </ul>
              </div><!--/.nav-collapse -->
            </div>
        </div>
    </div>

    <div class="container">    
    {% if user.is_authenticated %}
                Usuário Logado <i class="icon-user"></i>: 
                <span class="label badge-inverse">{{ user.username }}</span>&nbsp;
            {% else %}
                Usuário Logado <i class="icon-user"></i>: 
                <span class="label badge-inverse">Nenhum usuário logado</span>&nbsp;
            {% endif %}     
    {% block content %}
        <div class="content-center">

          <hr />
          <h1>Bem-vindo ao EventeX!</h1>
          <p>O evento mais sensacional do ano depois do Dev in Rio!</p>
          <p>Você não pode perder esta oportunidade!</p>
          <p>
            <a href="/inscricao/" class="btn btn-primary">Inscreva-se já...</a>
          </p>
          <p>Para dúvidas e mais informações entre em contato com <a href="#">eventext@eventext.com.br</a></p>

        </div><!-- <div class="content-center"> -->
        {% endblock content %}

      <hr>
      <footer>
          <p>
              <a href="http://estudepy.wordpress.com/" target="_blank">
                <img src="{{ STATIC_URL }}img/estudepy-logo.png" class="pull-left">
              </a>
              &nbsp;
              &copy; 2013. <a href="/">EventeX</a>, some rights reserved. &nbsp;
              <img src="{{ STATIC_URL }}img/80x15.png"> &nbsp;
              <a href="https://docs.djangoproject.com/en/1.5/"  target="_blank">
                <img src="{{ STATIC_URL }}img/djangosite100x25.gif" class="pull-right">
              </a>
          </p>
      </footer>

      <a href="https://github.com/fabianogoes/eventex" target="_blank">
          <img style="position: absolute; top: 0; right: 0; border: 0; z-index: 999999"
               src="{{ STATIC_URL }}img/forkme.png" alt="Fork me on GitHub">
      </a>

    </div> <!-- /container -->


<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">EventeX</h3>
  </div>
  <div class="modal-body">
    <p>
        Sistema desenvolvido durante o cursor:
        <strong>Welcome To The Django</strong> Turma 11
    </p>
    <p>
        <h3>Periodo:</h3>
        <ul>
            <li>21 de Julho de 2013 - domingo</li>
            <li>28 de Julho de 2013 - domingo</li>
            <li>04 de Agosto de 2013 - domingo</li>
            <li>11 de Agosto de 2013 - domingo</li>
        </ul>
    </p>
  </div>
  <div class="modal-footer">
    <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{{ STATIC_URL }}js/jquery.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap.js"></script>
<script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
<script src="{{ STATIC_URL }}js/holder.js"></script>
<script src="{{ STATIC_URL }}js/application.js"></script>


</body>
</html>

eventex/core/templates/index.html
{% extends 'base.html' %}

{% block content %}

    <div class="content-center">
      <div>
            <a href="/"><img src="{{ STATIC_URL }}img/logo.png" /></a>
      </div>
      <hr />
      <h1>Bem-vindo ao EventeX!</h1>
      <p>O evento mais sensacional do ano depois do Dev in Rio!</p>
      <p>Você não pode perder esta oportunidade!</p>
      <p>
        <a href="{% url 'subscriptions:subscribe' %}" class="btn btn-primary">Inscreva-se já...</a>
          <a href="/admin/subscriptions/subscription/" class="btn btn-primary" target="__blank">Lista de inscritos...</a>
      </p>
      <p>Para dúvidas e mais informações entre em contato com <a href="#">eventext@eventext.com.br</a></p>
    </div>

{% endblock content %}